import './globals.css'
import { Inter } from 'next/font/google';
import Navbar from './components/navbar/page';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Blog Post',
  description: 'Generated by Sanket K',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="manifest" href="/manifest.json" />
        <link rel="apple-touch-icon" href="/icon-512x512.png"></link>
        <meta name="theme-color" content="#000" />
      </head>
      <body className={inter.className}>
      <Navbar/>
      {children}
      </body>
    </html>
  )
}
